---
- name: setup node
  hosts: all
  tasks:

  - name: update all packages
    yum:
      name: '*'
      state: latest
    become: yes

  - name: install network tools
    yum:
      name: net-tools
    become: yes

  - name: install ntp
    yum:
      name: ntp
    become: yes

  - name: check ntpd service is running
    command: systemctl status ntpd
    register: result
    ignore_errors: True
    become: yes

  - name: configure and sync ntp
    command: "{{item}}"
    with_items:
      - chkconfig ntpd on
      - ntpdate pool.ntp.org
    when: result is failed
    become: yes

  - name: start service ntp, if not running
    service:
      name: ntpd
      state: started
    become: yes

  - name: turn off firewall for install
    command: systemctl disable firewalld
    become: yes

  - replace:
      path: /etc/fstab
      regexp: '^/dev/mapper/centos-swap\s*swap\s*swap\s*defaults\s*[0-9]\s*[0-9]$'
      replace: '# /dev/mapper/centos-swap swap                    swap    defaults        0 0'
    become: yes
